Update POOFITEE

diff --git a/POOFITEE b/POOFITEE
--- a/POOFITEE
+++ b/POOFITEE
@@ -182,85 +182,103 @@ what_needs_to_be_installed () {
 mailpath="${mailpath# }";mailpath="${mailpath%% *}";mailpath="${mailpath%%.*}" # note the unique filter here!!!!!!!!!!!!!!!!!!!!!!!!
 [[ -z "$postmappath" ]] && postmappath=$($whereispath $binaryflag postmap);postmappath="${postmappath#*:}";postmappath="${postmappath# }";postmappath="${postmappath%% *}"
 [[ -z "$postqueuepath" ]] && postqueuepath=$($whereispath $binaryflag postqueue);postqueuepath="${postqueuepath#*:}";postqueuepath="${postqueuepath# }";postqueuepath="${postqueuepath%% *}"
-if ! [[ -z "$1" ]] || [[ "$gawkpath" == "installandcheckme" ]];then
-     if ([[ "$1" == "checkawk" ]] && ! [[ "$gawkpath" == "checkedgood" ]]) || [[ "$gawkpath" == "installandcheckme" ]];then
+if ! [[ -z "$1" ]] || [[ "$gawkpath" == "installandcheckme" ]] || [[ "$mawkpath" == "installandcheckme" ]];then
+     if ! [[ "$gawkpath" == "checkedgood" ]] && ! [[ "$mawkpath" == "checkedgood" ]] && ([[ "$1" == "checkawk" ]] || [[ "$gawkpath" == "installandcheckme" ]] || [[ "$mawkpath" == "installandcheckme" ]]);then
           if [[ $answer =~ [fpe] ]] && ! [[ -z "$awkpath" ]];then
+              tailawktestpid="" # To make it survive the loop scope
               until false;do
 # Check here for awk functionality with stdbuf
-                  printf "Checking $([[ "$gawkpath" == "installandcheckme" ]] && printf "gawk and ")awk for functionality..."
+                  printf "Checking $([[ "$gawkpath" == "installandcheckme" ]] && printf "gawk$([[ "$mawkpath" == "installandcheckme" ]] && printf ", mawk,") and " || [[ "$mawkpath" == "installandcheckme" ]] && printf "mawk and ")awk for functionality..."
                   echo "" > awktestbed
                   $tailpath -fn0 awktestbed 2>/dev/null|$stdbufpath -o0 $awkpath '{print $1}' > awktestresults 2>/dev/null &
                   tailawktestpid="$!"
                   sleep 1
                   echo "testline" >> awktestbed
                   sleep 1
-#                  kill $tailawktestpid &>/dev/null
                   if ! [[ "$($tailpath -n1 awktestresults)" == "testline" ]];then #try/use gawk instead
                        gawkpath="$($whereispath $binaryflag gawk)";gawkpath="${gawkpath#*:}";gawkpath="${gawkpath# }";gawkpath="${gawkpath%% *}"
                        if ! [[ -z "$gawkpath" ]];then
-                            $tailpath -fn0 awktestbed 2>/dev/null|$stdbufpath -o0 $gawkpath '{print $1}' > awktestresults 2>/dev/null &
+                            kill $tailawktestpid &>/dev/null
+                            $tailpath -fn0 awktestbed 2>/dev/null|$stdbufpath -o0 $gawkpath '{print $1}' > awktestresults &
                             tailawktestpid="$!"
                             sleep 1
                             echo "testline" >> awktestbed
                             sleep 1
-#                            kill $tailawktestpid &>/dev/null
                        else
-#install gawk, then check gawk.  If success, change awkpath and break this loop
+#install gawk, then check gawk.  If success later, change awkpath
                             gawkpath="installandcheckme"
-                            break
                        fi
                        if ! [[ "$($tailpath -n1 awktestresults 2>/dev/null)" == "testline" ]];then #warn
-                            cat <<-EOF
-				WARNING:
-				One or more features that you selected will require another version of awk than
-				this system has currently - the version of $awkpath
-				on this system does not receive input via the stdbuf command like it will need 
-				to.  This is a common deficiency with some versions of awk.  This install script
-				is not advanced enough to locate the right version of awk to install for you.  
-				The best fix for this condition is that you manually upgrade awk or gawk, 
-				verifying that the new version succeeds with the code snippet below, then 
-				restart this poofitee installer again.  If you decide to keep your current
-				version[s] of awk/gawk and install a separate version for poofitee only so that
-				none of your other scripts run the new awk version that poofitee needs, restart 
-				this installer script with the command line argument added as follows:
+                            mawkpath="$($whereispath $binaryflag mawk)";mawkpath="${mawkpath#*:}";mawkpath="${mawkpath# }";mawkpath="${mawkpath%% *}"
+                            if ! [[ -z "$mawkpath" ]];then
+                                 kill $tailawktestpid &>/dev/null
+                                 $tailpath -fn0 awktestbed 2>/dev/null|$stdbufpath -o0 $mawkpath '{print $1}' > awktestresults 2>/dev/null &
+                                 tailawktestpid="$!"
+                                 sleep 1
+                                 echo "testline" >> awktestbed
+                                 sleep 1
+                            else
+#install mawk, then check mawk.  If success later, change awkpath and break this loop
+                                 mawkpath="installandcheckme"
+                                 break
+                            fi
+                            if ! [[ "$($tailpath -n1 awktestresults 2>/dev/null)" == "testline" ]];then #warn
+                                 if [[ "$gawkpath" != "installandcheckme" ]];then
+                                      cat <<-EOF
+					WARNING:
+					One or more features that you selected will require another version of awk than
+					this system has currently - the version of $awkpath
+					on this system does not receive input via the stdbuf command like it will need 
+					to.  This is a common deficiency with some versions of awk.  This install script
+					is not advanced enough to locate the right version of awk to install for you.  
+					The best fix for this condition is that you manually upgrade awk, mawk, or gawk, 
+					verifying that the new version succeeds with the code snippet below, then 
+					restart this poofitee installer again.  If you decide to keep your current
+					version[s] of awk/gawk and install a separate version for poofitee only so that
+					none of your other scripts run the new awk version that poofitee needs, restart 
+					this installer script with the command line argument added as follows:
 
-				poofitee awk=/path/and/awkfilename
+					poofitee awk=/substitute_real_path_here/substitute_gawk_mawk_awk_etc_here
 
-				You may use another terminal window to upgrade awk and resume in this one to see
-				if this script discovers the new awk version.  Code snippet will now follow,
-				EOF
-                            press_a_key
-                            cat <<-EOF
-				Here is the test instruction snippet that awk or gawk needs to succeed with:
+					You may use another terminal window to upgrade awk and resume in this one to see
+					if this script discovers the new awk version.  Code snippet will now follow,
+					adjust the awk name to what you install:
+					EOF
+                                      press_a_key
+                                      cat <<-EOF
+					Here is the test code snippet that awk, mawk, or gawk needs to succeed with:
 
-				echo "" > awktestbed
-				$tailpath -fn0 awktestbed 2>/dev/null|$stdbufpath -o0 awk '{print \$1}' > awktestresults 2>/dev/null &
-				tailawktestpid="\$!"
-				echo "testline" >> awktestbed
-				sleep 1
-				kill \$tailawktestpid &>/dev/null
-				if [[ -z "\$(cat awktestresults)" ]];then echo "This awk version fails";else echo "This awk version succeeds";fi
-				EOF
-                            press_a_key
-                            awkpath="$($whereispath $binaryflag awk)";awkpath="${awkpath#*:}";awkpath="${awkpath# }";awkpath="${awkpath%% *}"
+					echo "" > awktestbed
+					$tailpath -fn0 awktestbed 2>/dev/null|$stdbufpath -o0 awk '{print \$1}' > awktestresults 2>/dev/null &
+					tailawktestpid="\$!"
+					echo "testline" >> awktestbed
+					sleep 1
+					kill \$tailawktestpid &>/dev/null
+					if [[ -z "\$(cat awktestresults)" ]];then echo "This awk version fails";else echo "This awk version succeeds";fi
+					EOF
+                                      press_a_key
+                                 fi
+                            else
+                                 if ! [[ -z "$mawkpath" ]] && ! [[ "$mawkpath" == "" ]];then
+                                      awkpath="$mawkpath"
+                                      mawkpath="checkedgood"
+                                      gawkpath=""
+                                 fi
+                                 break
+                            fi
                        else
-                            kill $tailawktestpid &>/dev/null
-#                            rm awktestresults &>/dev/null
-                            rm awktestbed &>/dev/null
                             if ! [[ -z "$gawkpath" ]];then
                                  awkpath="$gawkpath"
                                  gawkpath="checkedgood"
                             fi
                             break
                        fi
-                  else
-                       gawkpath="checkedgood"
                   fi
-                  kill $tailawktestpid &>/dev/null
-#                  rm awktestresults &>/dev/null
-                  rm awktestbed &>/dev/null
                   break
               done
+              ! [[ -z $tailawktestpid ]] && kill $tailawktestpid &>/dev/null
+              rm awktestresults &>/dev/null
+              rm awktestbed &>/dev/null
           fi
      fi
 fi
@@ -277,12 +295,19 @@ fi
 if [[ $answer =~ p ]];then
      set_notinstalled_var # during development, just install everything
 fi
-notinstalled="$(printf "$notinstalled"|$sortpath|$uniqpath)\n"
+pronotinstalled="$(printf "$notinstalled"|$sortpath|$uniqpath)\n"
+# packages are in alpha order so duplicates got removed, now we need to rearrange to workable order
+# packages that need to be tried once and changed go first, then awk/gawk/mawk/nawk
+# netfilter-persistent first, then awk/gawk/mawk/nawk
+notinstalled="$(printf "$pronotinstalled\n"|while read package;do [[ "$package" == "netfilter-persistent" ]] && printf "$package\n";done)"
+notinstalled+="\n$(printf "$pronotinstalled\n"|while read package;do [[ "$package" != "netfilter-persistent" ]] && [[ "$package" =~ ^gawk$|^mawk$|^nawk$ ]] && printf "$package\n";done)"
+notinstalled+="\n$(printf "$pronotinstalled\n"|while read package;do [[ "$package" != "netfilter-persistent" ]] && ! [[ "$package" =~ ^gawk$|^mawk$|^nawk$ ]] && printf "$package\n";done)"
+notinstalled+="\n"
 not_installed_single_line="$(printf "$notinstalled"|$awkpath '{gsub("\\n"," ");printf $0" "}')"
 not_installed_single_line="${not_installed_single_line:: -1}"
 [ -z "$not_installed_single_line" ] && return 0
 return "$(printf "$notinstalled"|$wcpath -l)"
-}
+} 2>/dev/null #redirection needed because in my development environment mawk breaks pipe and spews out an error
 sendmail_works_or_not () {
 #functionize the following, name it 
 sendmail_works=""
@@ -449,6 +474,7 @@ EOF
 }
 set_notinstalled_var () {
 ! [[ -z "$gawkpath" ]] && [[ "$gawkpath" == "installandcheckme" ]] && notinstalled+="gawk\n"
+! [[ -z "$mawkpath" ]] && [[ "$mawkpath" == "installandcheckme" ]] && notinstalled+="mawk\n"
 [[ -z "$inotifywaitpath" ]] && notinstalled+="inotify-tools\n"
 [[ -z "$iptablespath" ]] && notinstalled+="iptables\n"
 [[ -z "$netfiltperspath" ]] && notinstalled+="netfilter-persistent\n"
@@ -2644,6 +2670,7 @@ else
 fi
 #force these to be global variables, we need them to perform the install:
 gawkpath=""
+mawkpath=""
 pythonpath="$($whereispath $binaryflag python)"
 pythonpath="${pythonpath#*:}";pythonpath="${pythonpath# }";pythonpath="${pythonpath%% *}"
 greppath="$($whereispath $binaryflag grep)"
@@ -2977,8 +3004,8 @@ until ! [ -z $answer ];do
 #        fi
 # Might need to manually add to /etc/network/interfaces: pre-down /etc/init.d/netfilter-persistent save
             clear
-            if ! [[ -z "$installerpath" ]] && ! [[ -z "$not_installed_single_line" ]];then # install what is neededpress 
-                 if [ -z $been_here_before ];then
+            if ! [ -z "$installerpath" ] && ! [ -z "$not_installed_single_line" ];then # install what is neededpress 
+                 if [ -z "$been_here_before" ];then
                       ensure_connection
                       if [[ "$installerpath" =~ apt-get ]];then
                            printf "Installation of\n$notinstalled\n\nis required next.  Press u to update your system's package installer first,\
@@ -3008,8 +3035,44 @@ until ! [ -z $answer ];do
                       fi
                  fi
                  printf "\nInstalling\n"
-                 eval "$xargspath -a <(printf $not_installed_single_line) -r -- sudo $installerpath" 2>/dev/null
+                 eval "$xargspath -a <(printf "$not_installed_single_line") -r -- sudo $installerpath" 2>/dev/null
                  what_needs_to_be_installed &>/dev/null
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+# LAST UNTESTED CHANGE WAS TO DOUBLE QUOTE $not_installed_single_line IN THE INSTALL LINES
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
 # make the following into a function
 #switch_from_more_common_package_to_less_common_package dnsutils dig ldns drill
 #switch_from_more_common_package_to_less_common_package netfilter-persistent netfilter-persistent iptables-persistent iptables-persistent
@@ -3020,7 +3083,7 @@ until ! [ -z $answer ];do
                            digpath=$($whereispath $binaryflag drill);digpath="${digpath#*:}";digpath="${digpath# }";digpath="${digpath%% *}"
 #                           printf "...Not a problem...\n"
                            if [[ -z $digpath ]];then
-                                 eval "$xargspath -a <(printf $not_installed_single_line|$sedpath 's/dnsutils/ldns/1') -r -- sudo $installerpath"
+                                 eval "$xargspath -a <(printf ""|$sedpath 's/dnsutils/ldns/1') -r -- sudo $installerpath"
                                  digpath=$($whereispath $binaryflag drill);digpath="${digpath#*:}";digpath="${digpath# }";digpath="${digpath%% *}"
                                  what_needs_to_be_installed
                                  dnsutils_already_given_a_chance=""
@@ -3029,13 +3092,18 @@ until ! [ -z $answer ];do
                            dnsutils_already_given_a_chance="anyvaluewillwork"
                       fi
                  fi
+
+
+
+
+
                  if [[ "$not_installed_single_line" =~ ^netfilter-persistent ]];then
                       if ! [[ -z "$netfilter_persistent_already_given_a_chance" ]];then
                            netfilter_persistent_already_given_a_chance=""
                            iptabsavepath=$($whereispath $binaryflag iptables-save);iptabsavepath="${iptabsavepath#*:}";iptabsavepath="${iptabsavepath# }";iptabsavepath="${iptabsavepath%% *}"
 #                           printf "...Not a problem...\n"
                            if [[ -z "$iptabsavepath" ]];then
-                                 eval "$xargspath -a <(printf $not_installed_single_line|$sedpath 's/netfilter/iptables/1') -r -- sudo $installerpath"
+                                 eval "$xargspath -a <(printf "$not_installed_single_line"|$sedpath 's/netfilter/iptables/1') -r -- sudo $installerpath"
                                  iptabsavepath=$($whereispath $binaryflag iptables-save);iptabsavepath="${iptabsavepath#*:}";iptabsavepath="${iptabsavepath# }";iptabsavepath="${iptabsavepath%% *}"
                                  netfiltperspath=$($whereispath $binaryflag iptables-restore);netfiltperspath="${netfiltperspath#*:}";netfiltperspath="${netfiltperspath# }";netfiltperspath="${netfiltperspath%% *}"
                                  what_needs_to_be_installed
@@ -3047,6 +3115,11 @@ until ! [ -z $answer ];do
                            netfilter_persistent_already_given_a_chance="anyvaluewillwork"
                       fi
                  fi
+
+
+
+
+
                  if [ $? != "0" ] && [ -z "$previous_not_installed" ] || [ "$(what_needs_to_be_installed;echo "$?")" != "$previous_not_installed" ];then
                       : # keep looping as long as progress is being detected
                       previous_not_installed="$(what_needs_to_be_installed;echo "$?")"
