Update POOFITEE

diff --git a/POOFITEE b/POOFITEE
--- a/POOFITEE
+++ b/POOFITEE
@@ -814,9 +814,30 @@ if ! [[ -z "$likeliest_internal_net_interface" ]] && [[ "$($greppath -c ^net.ipv
           [[ $iptables_masquerading == false ]] && ([[ "$($iptablespath -wt nat -I POSTROUTING 1  -o $external_net_interface  -p all -j MASQUERADE -m comment --comment "by installer request during poofitee_firewall installation";echo $?)" == "0" ]] || printf "\n\nUnable to make the change in iptables")
      fi
 fi
+# in Ubuntu 15.10 and in /usr/share/netfilter-persistent/plugins.d there is a file called 15-ip4tables that needs to be edited: 
+# insert line following load_rules() and { lines
+# $sedpath -i $($greppath --line-numb -m 1 "^load_rules()" /usr/share/netfilter-persistent/plugins.d/15-ip4tables|$awkpath '{print $1+2}') /usr/share/netfilter-persistent/plugins.d/15-ip4tables
+#
+       if ! ($greppath -- "ipset restore -f /etc/iptables/ipset.sets" /usr/share/netfilter-persistent/plugins.d/15-ip4tables) && ed /usr/share/netfilter-persistent/plugins.d/15-ip4tables <<-LOAD_RULES
+	"$($greppath --line-numb -m 1 "^load_rules()" /usr/share/netfilter-persistent/plugins.d/15-ip4tables|$awkpath '{print $1+2"i";exit}')"
+	# load rules made with ipset
+	ipset restore -f /etc/iptables/ipset.sets
+	.
+	w
+	q
+	LOAD_RULES
+       if ! ($greppath -- "ipset save -f /etc/iptables/ipset.sets" /usr/share/netfilter-persistent/plugins.d/15-ip4tables) && ed /usr/share/netfilter-persistent/plugins.d/15-ip4tables <<-SAVE_RULES
+	"$($greppath --line-numb -m 1 "^save_rules()" /usr/share/netfilter-persistent/plugins.d/15-ip4tables|$awkpath '{print $1+2"i";exit}')"
+	# save rules made with ipset	
+	ipset save -f /etc/iptables/ipset.sets
+	.
+	w
+	q
+	SAVE_RULES
 
             (cat <<-BUILDIPTABLES.SH_END
 	#!/bin/bash
+	ipset create blacklist hash:ip >/dev/null 2>/dev/null
 	$iptablespath -wP OUTPUT ACCEPT
 	$iptablespath -wN poofitee_fw_d_blacklist  2>/dev/null
 	$iptablespath -wN poofitee_fw_d_privateIPs  2>/dev/null
@@ -834,26 +855,29 @@ fi
 
 	! [ -z "$likeliest_internal_net_interface" ] && ! ($iptablespath -wnvL INPUT|$greppath -- "-i $(echo "$internal_net_interface"|$awkpath '{print $1;exit 0}')"|$greppath -- "-p all"|$greppath -- "-j ACCEPT"|$greppath "poofitee_firewall") && ($iptablespath -wA INPUT -i $(echo "$internal_net_interface"|$awkpath '{print $1;exit 0}') -j ACCEPT -m comment --comment "poofitee_firewall"  2>/dev/null || printf "Failed")
 
-	! ($iptablespath -wnvL INPUT|$greppath -- "-p all"|$greppath -- "-j poofitee_fw_s_static_trusted"|$greppath "poofitee_firewall") && ($iptablespath -wA INPUT -j poofitee_fw_s_static_trusted -m comment --comment "poofitee_firewall"  2>/dev/null || printf "Failed")
-	! ($iptablespath -wnvL INPUT|$greppath -- "-p all"|$greppath -- "-j poofitee_fw_s_whitelist"|$greppath "poofitee_firewall") && ($iptablespath -wA INPUT -j poofitee_fw_s_whitelist -m comment --comment "poofitee_firewall"  2>/dev/null || printf "Failed")
-	! ($iptablespath -wnvL INPUT|$greppath -- "-p all"|$greppath -- "-j poofitee_fw_s_blacklist"|$greppath "poofitee_firewall") && ($iptablespath -wA INPUT -j poofitee_fw_s_blacklist -m comment --comment "poofitee_firewall"  2>/dev/null || printf "Failed")
-	! ($iptablespath -wnvL INPUT|$greppath -- "-p all"|$greppath -- "-j LOG --log-level 4 --log-prefix \"INPUT chain termed \""|$greppath "poofitee_firewall") && ($iptablespath -wA INPUT -i $external_net_interface -j LOG --log-level 4 --log-prefix "INPUT chain termed " -m comment --comment "poofitee_firewall"  2>/dev/null || printf "Failed")
-	! ($iptablespath -wnvL INPUT|$greppath -- "-p all"|$greppath -- "-j DROP"|$greppath "poofitee_firewall") && ($iptablespath -wA INPUT -i $external_net_interface -j DROP -m comment --comment "poofitee_firewall"  2>/dev/null || printf "Failed")
-	! ($iptablespath -wnvL OUTPUT|$greppath -- "-o $external_net_interface"|$greppath -- "-p all"|$greppath -- "-j poofitee_fw_d_static_trusted"|$greppath "poofitee_firewall") && ($iptablespath -wA OUTPUT -o $external_net_interface -j poofitee_fw_d_static_trusted -m comment --comment "poofitee_firewall"  2>/dev/null || printf "Failed")
-	! ($iptablespath -wnvL OUTPUT|$greppath -- "-o $external_net_interface"|$greppath -- "-p all"|$greppath -- "-j poofitee_fw_d_whitelist"|$greppath "poofitee_firewall") && ($iptablespath -wA OUTPUT -o $external_net_interface -j poofitee_fw_d_whitelist -m comment --comment "poofitee_firewall"  2>/dev/null || printf "Failed")
-	! ($iptablespath -wnvL OUTPUT|$greppath -- "-o $external_net_interface"|$greppath -- "-p all"|$greppath -- "-j poofitee_fw_d_blacklist"|$greppath "poofitee_firewall") && ($iptablespath -wA OUTPUT -o $external_net_interface -j poofitee_fw_d_blacklist -m comment --comment "poofitee_firewall"  2>/dev/null || printf "Failed")
-	! ($iptablespath -wnvL OUTPUT|$greppath -- "-o $external_net_interface"|$greppath -- "-p all"|$greppath -- "-j poofitee_fw_d_privateIPs"|$greppath "poofitee_firewall") && ($iptablespath -wA OUTPUT -o $external_net_interface -j poofitee_fw_d_privateIPs -m comment --comment "poofitee_firewall"  2>/dev/null || printf "Failed")
-	! ($iptablespath -wnvL poofitee_fw_d_privateIPs|$greppath -- "-o $external_net_interface"|$greppath -- "-p all"|$greppath -- "-j DROP"|$greppath "poofitee_firewall"|$greppath -- "-d 10.0.0.0/8") && ($iptablespath -wA poofitee_fw_d_privateIPs -d 10.0.0.0/8 -m comment --comment "poofitee_firewall_private IPs" -j DROP  2>/dev/null || printf "Failed")
-	! ($iptablespath -wnvL poofitee_fw_d_privateIPs|$greppath -- "-o $external_net_interface"|$greppath -- "-p all"|$greppath -- "-j DROP"|$greppath "poofitee_firewall"|$greppath -- "-d 172.16.0.0/12") && ($iptablespath -wA poofitee_fw_d_privateIPs -d 172.16.0.0/12 -m comment --comment "poofitee_firewall_private IPs" -j DROP  2>/dev/null || printf "Failed")
-	! ($iptablespath -wnvL poofitee_fw_d_privateIPs|$greppath -- "-o $external_net_interface"|$greppath -- "-p all"|$greppath -- "-j DROP"|$greppath "poofitee_firewall"|$greppath -- "-d 192.168.0.0/16") && ($iptablespath -wA poofitee_fw_d_privateIPs -d 192.168.0.0/16 -m comment --comment "poofitee_firewall_private IPs" -j DROP  2>/dev/null || printf "Failed")
-	! ($iptablespath -wnvL poofitee_fw_s_privateIPs|$greppath -- "-i $external_net_interface"|$greppath -- "-p all"|$greppath -- "-j DROP"|$greppath "poofitee_firewall"|$greppath -- "-s 10.0.0.0/8") && ($iptablespath -wA poofitee_fw_s_privateIPs -s 10.0.0.0/8  -m comment --comment "poofitee_firewall_private IPs" -j DROP  2>/dev/null || printf "Failed")
-	! ($iptablespath -wnvL poofitee_fw_s_privateIPs|$greppath -- "-i $external_net_interface"|$greppath -- "-p all"|$greppath -- "-j DROP"|$greppath "poofitee_firewall"|$greppath -- "-s 172.16.0.0/12") && ($iptablespath -wA poofitee_fw_s_privateIPs -s 172.16.0.0/12 -m comment --comment "poofitee_firewall_private IPs" -j DROP  2>/dev/null || printf "Failed")
-	! ($iptablespath -wnvL poofitee_fw_s_privateIPs|$greppath -- "-i $external_net_interface"|$greppath -- "-p all"|$greppath -- "-j DROP"|$greppath "poofitee_firewall"|$greppath -- "-s 192.168.0.0/16") && ($iptablespath -wA poofitee_fw_s_privateIPs -s 192.168.0.0/16 -m comment --comment "poofitee_firewall_private IPs" -j DROP  2>/dev/null || printf "Failed")
-	! ($iptablespath -wnvL poofitee_fw_s_static_trusted|$greppath -- "-s 91.189.88.0/21"|$greppath -- "-p all"|$greppath -- "-j ACCEPT"|$greppath "poofitee_firewall") && ($iptablespath -wA poofitee_fw_s_static_trusted -s 91.189.88.0/21 -m comment --comment "poofitee_firewall Canonical" -j ACCEPT  2>/dev/null || printf "Failed")
-	! ($iptablespath -wnvL poofitee_fw_s_static_trusted|$greppath -- "-i lo"|$greppath -- "-p all"|$greppath -- "-j ACCEPT") && ($iptablespath -wA poofitee_fw_s_static_trusted -i lo -m comment --comment "poofitee_firewall we really have to trust localhost at this level" -j ACCEPT  2>/dev/null || printf "Failed")
-	! ($iptablespath -wnvL poofitee_fw_s_static_trusted|$greppath -- "RELATED,ESTABLISHED"|$greppath -- "-p all"|$greppath -- "-j ACCEPT"|$greppath "poofitee_firewall") && ($iptablespath -wA poofitee_fw_s_static_trusted -m conntrack --ctstate RELATED,ESTABLISHED -m comment --comment "poofitee_firewall existing dialogs traffic presumed trusted" -j ACCEPT  2>/dev/null || printf "Failed")
-	# ! ($iptablespath -wnvL poofitee_fw_d_static_trusted|$greppath -- "-d 199.102.46.70"|$greppath -- "-p all"|$greppath -- "-j ACCEPT"|$greppath "poofitee_firewall") && ($iptablespath -wA poofitee_fw_d_static_trusted -d 199.102.46.70 -m comment --comment "poofitee_firewall_local time server hosted by Monticello" -j ACCEPT  2>/dev/null || printf "Failed")
+	! ($iptablespath -wnvL INPUT                         |$greppath -- " poofitee_fw_s_static_trusted  all  --  "                                                                |$greppath "poofitee_firewall") && ($iptablespath -wA INPUT -j poofitee_fw_s_static_trusted -m comment --comment "poofitee_firewall"  2>/dev/null || printf "Failed")
+	! ($iptablespath -wnvL INPUT                         |$greppath -- " poofitee_fw_s_whitelist  all  --  "                                                                     |$greppath "poofitee_firewall") && ($iptablespath -wA INPUT -j poofitee_fw_s_whitelist -m comment --comment "poofitee_firewall"  2>/dev/null || printf "Failed")
+	! ($iptablespath -wnvL INPUT                         |$greppath -- " poofitee_fw_s_privateIPs  all  --  $external_net_interface"                                             |$greppath "poofitee_firewall") && ($iptablespath -wA INPUT -i $external_net_interface -j poofitee_fw_s_privateIPs -m comment --comment "poofitee_firewall"  2>/dev/null || printf "Failed")
+	! ($iptablespath -wnvL INPUT                         |$greppath -- " DROP       all  --  "                                           |$greppath -- " match-set blacklist src"|$greppath "poofitee_firewall") && ($iptablespath -wA INPUT -m set --match-set blacklist src -j DROP -m comment --comment "poofitee_firewall"
+	! ($iptablespath -wnvL INPUT                         |$greppath -- " poofitee_fw_s_blacklist  all  --  "                                                                     |$greppath "poofitee_firewall") && ($iptablespath -wA INPUT -j poofitee_fw_s_blacklist -m comment --comment "poofitee_firewall"  2>/dev/null || printf "Failed")
+	! ($iptablespath -wnvL INPUT                         |$greppath -- " LOG        all  --  "                |$greppath -- " --log-level 4 --log-prefix \"INPUT chain termed \""|$greppath "poofitee_firewall") && ($iptablespath -wA INPUT -i $external_net_interface -j LOG --log-level 4 --log-prefix "INPUT chain termed " -m comment --comment "poofitee_firewall"  2>/dev/null || printf "Failed")
+	! ($iptablespath -wnvL INPUT                         |$greppath -- " DROP       all  --  "                                                                                   |$greppath "poofitee_firewall"|$greppath -v ) && ($iptablespath -wA INPUT -i $external_net_interface -j DROP -m comment --comment "poofitee_firewall"  2>/dev/null || printf "Failed")
+	! ($iptablespath -wnvL poofitee_fw_s_privateIPs      |$greppath -- " DROP       all  --  $external_net_interface"                                 |$greppath -- " 10.0.0.0/8"|$greppath "poofitee_firewall") && ($iptablespath -wA poofitee_fw_s_privateIPs -i $external_net_interface -s 10.0.0.0/8  -m comment --comment "poofitee_firewall_private IPs" -j DROP  2>/dev/null || printf "Failed")
+	! ($iptablespath -wnvL poofitee_fw_s_privateIPs      |$greppath -- " DROP       all  --  $external_net_interface"                              |$greppath -- " 172.16.0.0/12"|$greppath "poofitee_firewall") && ($iptablespath -wA poofitee_fw_s_privateIPs -i $external_net_interface -s 172.16.0.0/12 -m comment --comment "poofitee_firewall_private IPs" -j DROP  2>/dev/null || printf "Failed")
+	! ($iptablespath -wnvL poofitee_fw_s_privateIPs      |$greppath -- " DROP       all  --  $external_net_interface"                             |$greppath -- " 192.168.0.0/16"|$greppath "poofitee_firewall") && ($iptablespath -wA poofitee_fw_s_privateIPs -i $external_net_interface -s 192.168.0.0/16 -m comment --comment "poofitee_firewall_private IPs" -j DROP  2>/dev/null || printf "Failed")
+      # ! ($iptablespath -wnvL poofitee_fw_s_static_trusted  |$greppath -- " ACCEPT     all  --  "                                                   |$greppath -- " 91.189.88.0/21 "|$greppath "poofitee_firewall") && ($iptablespath -wA poofitee_fw_s_static_trusted -s 91.189.88.0/21 -m comment --comment "poofitee_firewall Canonical" -j ACCEPT  2>/dev/null || printf "Failed")
+	! ($iptablespath -wnvL poofitee_fw_s_static_trusted  |$greppath -- " ACCEPT     all  --  lo  "                                                                                                             ) && ($iptablespath -wA poofitee_fw_s_static_trusted -i lo -m comment --comment "poofitee_firewall we really have to trust localhost at this level" -j ACCEPT  2>/dev/null || printf "Failed")
+	! ($iptablespath -wnvL poofitee_fw_s_static_trusted  |$greppath -- " ACCEPT     all  --  "                                               |$greppath -- " RELATED,ESTABLISHED"|$greppath "poofitee_firewall") && ($iptablespath -wA poofitee_fw_s_static_trusted -m conntrack --ctstate RELATED,ESTABLISHED -m comment --comment "poofitee_firewall existing dialogs traffic presumed trusted" -j ACCEPT  2>/dev/null || printf "Failed")
 
+	! ($iptablespath -wnvL poofitee_fw_d_privateIPs      |$greppath -- " DROP       all  --  *      $external_net_interface"                          |$greppath -- " 10.0.0.0/8"|$greppath "poofitee_firewall") && ($iptablespath -wA poofitee_fw_d_privateIPs -o $external_net_interface -d 10.0.0.0/8 -m comment --comment "poofitee_firewall_private IPs" -j DROP  2>/dev/null || printf "Failed")
+	! ($iptablespath -wnvL poofitee_fw_d_privateIPs      |$greppath -- " DROP       all  --  *      $external_net_interface"                       |$greppath -- " 172.16.0.0/12"|$greppath "poofitee_firewall") && ($iptablespath -wA poofitee_fw_d_privateIPs -o $external_net_interface -d 172.16.0.0/12 -m comment --comment "poofitee_firewall_private IPs" -j DROP  2>/dev/null || printf "Failed")
+	! ($iptablespath -wnvL poofitee_fw_d_privateIPs      |$greppath -- " DROP       all  --  *      $external_net_interface"                      |$greppath -- " 192.168.0.0/16"|$greppath "poofitee_firewall") && ($iptablespath -wA poofitee_fw_d_privateIPs -o $external_net_interface -d 192.168.0.0/16 -m comment --comment "poofitee_firewall_private IPs" -j DROP  2>/dev/null || printf "Failed")
+      # ! ($iptablespath -wnvL poofitee_fw_d_static_trusted  |$greppath -- " ACCEPT     all  --  "                                                     |$greppath -- " 199.102.46.70"|$greppath "poofitee_firewall") && ($iptablespath -wA poofitee_fw_d_static_trusted -d 199.102.46.70 -m comment --comment "poofitee_firewall_local time server hosted by Monticello" -j ACCEPT  2>/dev/null || printf "Failed")
+	! ($iptablespath -wnvL OUTPUT                        |$greppath -- " DROP       all  --  "                                           |$greppath -- " match-set blacklist dst"|$greppath "poofitee_firewall") && ($iptablespath -wA OUTPUT -m set --match-set blacklist dst -j DROP -m comment --comment "poofitee_firewall"
+	! ($iptablespath -wnvL OUTPUT                        |$greppath -- " poofitee_fw_d_static_trusted  all  --  *      $external_net_interface"                                  |$greppath "poofitee_firewall") && ($iptablespath -wA OUTPUT -o $external_net_interface -j poofitee_fw_d_static_trusted -m comment --comment "poofitee_firewall"  2>/dev/null || printf "Failed")
+	! ($iptablespath -wnvL OUTPUT                        |$greppath -- " poofitee_fw_d_whitelist  all  --  *      $external_net_interface"                                       |$greppath "poofitee_firewall") && ($iptablespath -wA OUTPUT -o $external_net_interface -j poofitee_fw_d_whitelist -m comment --comment "poofitee_firewall"  2>/dev/null || printf "Failed")
+	! ($iptablespath -wnvL OUTPUT                        |$greppath -- " poofitee_fw_d_blacklist  all  --  *      $external_net_interface"                                       |$greppath "poofitee_firewall") && ($iptablespath -wA OUTPUT -o $external_net_interface -j poofitee_fw_d_blacklist -m comment --comment "poofitee_firewall"  2>/dev/null || printf "Failed")
+	! ($iptablespath -wnvL OUTPUT                        |$greppath -- " poofitee_fw_d_privateIPs  all  --  *      $external_net_interface"                                      |$greppath "poofitee_firewall") && ($iptablespath -wA OUTPUT -o $external_net_interface -j poofitee_fw_d_privateIPs -m comment --comment "poofitee_firewall"  2>/dev/null || printf "Failed")
 	BUILDIPTABLES.SH_END
 	) > "$poofitee_home_dir/preparedness/buildiptables.sh"
 	break
