Update POOFITEE

diff --git a/POOFITEE b/POOFITEE
--- a/POOFITEE
+++ b/POOFITEE
@@ -84,7 +84,6 @@ get_operator_knock_choices () {
                  i=1
                  while knockport[$i]="";printf "\n";read -e -p "Knock $i port:" knockport[$i];! [[ -z "${knockport[$i]}" ]];do
                       if ! [[ "${knockport[$i]}" =~ ^[0-9]{1,5}$ ]] || ! [[ $(( ${knockport[$i]} )) -le 65535 ]];then continue;fi
-#                      printf "${knockport[$i]}"
                       if ! [[ -z "$internal_net_interface" ]] && [[ -f "/etc/ssh/sshd_config" ]] && [[ "$($greppath ^Port /etc/ssh/sshd_config|$awkpath '{print $2}')" =~ [0-9] ]] && [[ " ${knockport[$i]} " =~ \ $($greppath ^Port /etc/ssh/sshd_config|$awkpath '{print $2}')\  ]];then
                          printf "You are advised against specifying your ssh port "$(printf "("$($greppath ^Port /etc/ssh/sshd_config|$awkpath \
 '{printf $2}')")")" simply because it will\
@@ -97,7 +96,6 @@ get_operator_knock_choices () {
 \niptables matching options beyond this, if you know them, except the -j target,\
 \n-g chain, -m recent, and -m comment iptables modules/options):\n\
 \n";knockproto[$i]="-p tcp --syn ";read -e -i "${knockproto[$i]}" knockproto[$i]
-#                      printf -- "\n${knockproto[$i]}\n"
                       testtarget[$i]=" -j DROP"
                       if [[ "${knockproto[$i]}" =~ \ --tcp-flags\ .*ACK\ .*ACK ]] ; then
 #                      if [[ "${knockproto[$i]}" =~ \ --tcp-flags\ *[^[:space:]g]*\ *ACK\  ]] ; then
@@ -130,12 +128,12 @@ printf ", and of course only if the previous\nknocks in the sequence have been r
                           printf -- "Your ${knockproto[$i]} is not crafted well enough, try again\n"
                           continue
                       fi
+                      if [[ "x$1$2$3" =~ unique ]] && ! [[ "$(i=1;while ! [[ -z "${knockproto[$i]}" ]];do printf -- "${knockproto[$i]}";printf "\n";i=$(($i + 1));done|$sortpath|$uniqpath -d|wc -l)" == "0" ]];then
+                          printf -- "\nYour ${knockproto[$i]} is required to be unique and is not, try again\n"
+                          continue
+                      fi
                       i=$(( $i+1 ));[[ $(( $i )) -gt 16 ]] && break
                  done
-                 for (( j=1;j<i;j++ )); do
-                      printf "$iptablespath -wA poofitee_knockstage$j${knockproto[$j]}\n"
-                 done
-
 }
 move_cursor_to_next_entry_in_list () {
 line=""
@@ -247,6 +245,7 @@ get_sendto_emailadds () {  # can take one optional arg, "onlyneed1" which will c
 install_port_knocking () {
             REPLY=""
             until [[ "$REPLY" =~ [yn] ]]; do
+               echo "The OTF feature is not yet finished.  Don't count on it..."
                read -e -r -n1 -p "Use OTPs (One-Time-Passwords)? (y, n, or ? for help) Client side is not free:"
                REPLY="${REPLY,}"
                [[ "$REPLY" =~ \? ]] && ( \
@@ -389,90 +388,67 @@ HOLD_UNTIL_ABLE
 #write rules to iptables rule set
             if [[ $REPLY == "l" ]];then
                  if_first_knock_is_ACK_message=""
-                 get_operator_knock_choices
-                 echo "Setting loose rules here...not yet developed.  Sorry"
-                 continue
-<<EOF
-INPUT
--m conntrack -ctstate NEW -j poofitee_knock_check
-
-poofitee_knock_check
--p 1-100 --dpt port1 -m recent --name poofitee_knock_port1 --rcheck -j RETURN
--p 1-100 --dpt port2 -m recent --name poofitee_knock_port2 --rcheck -j RETURN
--p 1-100 --dpt port3 -m recent --name poofitee_knock_port3 --rcheck -j RETURN
--p 1-100 --dpt port4 -m recent --name poofitee_knock_port4 --rcheck -j RETURN
--p 1-100 --dpt port5 -m recent --name poofitee_knock_port5 --rcheck -j RETURN
--p 1-100 --dpt port6 -m recent --name poofitee_knock_port6 --rcheck -j RETURN
--p 1-100 --dpt port7 -m recent --name poofitee_knock_port7 --rcheck -j RETURN
--p 1-100 --dpt port8 -m recent --name poofitee_knock_port8 --rcheck -j RETURN
--p 1-100 --dpt port9 -m recent --name poofitee_knock_port9 --rcheck -j RETURN
--p 1-100 --dpt port10 -m recent --name poofitee_knock_port10 --rcheck -j RETURN
--p 1-100 --dpt port11 -m recent --name poofitee_knock_port11 --rcheck -j RETURN
--p 1-100 --dpt port12 -m recent --name poofitee_knock_port12 --rcheck -j RETURN
--p 1-100 --dpt port13 -m recent --name poofitee_knock_port13 --rcheck -j RETURN
--p 1-100 --dpt port14 -m recent --name poofitee_knock_port14 --rcheck -j RETURN
--p 1-100 --dpt port15 -m recent --name poofitee_knock_port15 --rcheck -j RETURN
--p 1-100 --dpt port16 -m recent --name poofitee_knock_port16 --rcheck -j RETURN
-#at this point: tossed out packets that knocked same knock over
-#next goal: toss out packets not knocking at all
--p 1-100 --dpt port1 -m recent --name poofitee_knock_port1 --set -j poofitee_knock_new_knock
--p 1-100 --dpt port2 -m recent --name poofitee_knock_port2 --set -j poofitee_knock_new_knock
--p 1-100 --dpt port3 -m recent --name poofitee_knock_port3 --set -j poofitee_knock_new_knock
--p 1-100 --dpt port4 -m recent --name poofitee_knock_port4 --set -j poofitee_knock_new_knock
--p 1-100 --dpt port5 -m recent --name poofitee_knock_port5 --set -j poofitee_knock_new_knock
--p 1-100 --dpt port6 -m recent --name poofitee_knock_port6 --set -j poofitee_knock_new_knock
--p 1-100 --dpt port7 -m recent --name poofitee_knock_port7 --set -j poofitee_knock_new_knock
--p 1-100 --dpt port8 -m recent --name poofitee_knock_port8 --set -j poofitee_knock_new_knock
--p 1-100 --dpt port9 -m recent --name poofitee_knock_port9 --set -j poofitee_knock_new_knock
--p 1-100 --dpt port10 -m recent --name poofitee_knock_port10 --set -j poofitee_knock_new_knock
--p 1-100 --dpt port11 -m recent --name poofitee_knock_port11 --set -j poofitee_knock_new_knock
--p 1-100 --dpt port12 -m recent --name poofitee_knock_port12 --set -j poofitee_knock_new_knock
--p 1-100 --dpt port13 -m recent --name poofitee_knock_port13 --set -j poofitee_knock_new_knock
--p 1-100 --dpt port14 -m recent --name poofitee_knock_port14 --set -j poofitee_knock_new_knock
--p 1-100 --dpt port15 -m recent --name poofitee_knock_port15 --set -j poofitee_knock_new_knock
--p 1-100 --dpt port16 -m recent --name poofitee_knock_port16 --set -j poofitee_knock_new_knock
-#at this point: tossed out packets that knocked same knock over and those not knocking at all, knockers thrown into poofitee_knock_new_knock with them added to their new list
-#end of this chain
-# remaining source address gets one additional grade level towards graduation
-#next goal: determine highest knock level then reap.  seconds for reaping are calulated at knock configure time for x times n
-poofitee_knock_new_knock
--m recent --name poofitee_knock_senior --rcheck --seconds x*n --reap -j poofitee_knock_authorize
--m recent --name poofitee_knock_junior --rcheck --seconds x*n --reap -j poofitee_knock_seniorize
--m recent --name poofitee_knock_sophomore --rcheck --seconds x*n --reap -j poofitee_knock_juniorize
--m recent --name poofitee_knock_freshman --rcheck --seconds x*n --reap -j poofitee_knock_sophomorize
--m recent --name poofitee_knock_freshman --set -j LOG --log-prefix "poofitee knock freshman " -m comment --comment "poofitee_knock:This will schedule its blacklisting for couple mins from now"
--j poofitee_knock_portcustomexit
-poofitee_knock_authorize
--m recent --name poofitee_authorized --set -j LOG --log-prefix "poofitee knock authorized "
--m recent --name poofitee_knock_authorized --set -j poofitee_knock_portcustomexit
-poofitee_knock_seniorize
--m recent --name poofitee_knock_senior --set -j LOG --log-prefix "poofitee knock senior " -m comment --comment "poofitee_knock"
--j poofitee_knock_portcustomexit
-poofitee_knock_juniorize
--m recent --name poofitee_knock_junior --set -j LOG --log-prefix "poofitee knock junior " -m comment --comment "poofitee_knock"
--j poofitee_knock_portcustomexit
-poofitee_knock_sophomorize
--m recent --name poofitee_knock_sophomore --set -j LOG --log-prefix "poofitee knock sophomore " -m comment --comment "poofitee_knock"
--j poofitee_knock_portcustomexit
-poofitee_knock_portcustomexit
--p 1-100 --dpt port1 -j customexit_
--p 1-100 --dpt port2 -j customexit_
--p 1-100 --dpt port3 -j customexit_
--p 1-100 --dpt port4 -j customexit_
--p 1-100 --dpt port5 -j customexit_
--p 1-100 --dpt port6 -j customexit_
--p 1-100 --dpt port7 -j customexit_
--p 1-100 --dpt port8 -j customexit_
--p 1-100 --dpt port9 -j customexit_
--p 1-100 --dpt port10 -j customexit_
--p 1-100 --dpt port11 -j customexit_
--p 1-100 --dpt port12 -j customexit_
--p 1-100 --dpt port13 -j customexit_
--p 1-100 --dpt port14 -j customexit_
--p 1-100 --dpt port15 -j customexit_
--p 1-100 --dpt port16 -j customexit_
-
-EOF
+                 get_operator_knock_choices unique
+                 for (( j=1;j<i;j++ )); do
+                      printf "$iptablespath -wA poofitee_knockstage$j${knockproto[$j]}\n"
+                 done
+printf "\n\nYour current iptables ruleset is about to be changed to reflect your knock\
+\nentries just made.  The following changes are about to be made:\
+\n\n  -- All INPUT chain rules will be removed that contain the string\
+\n        \"poofitee_knock\" in their comment\
+\n\n  -- INPUT chain will receive all new knock rules that belong there, being\
+\n        placed adjacent and prior to current non-knock rules referencing the\
+\n        respective interface\
+\n\n  -- Poofitee chains knock_check, knock_new_knock, knock_portcustomexit,\
+\n        and others will be created new\
+\n\n  -- Poofitee chains knockerreap, knockersort, knockers, and all knockstages\
+\n        will be de-referenced and abandoned without flushing.  They are only\
+\n        used in the strict knock ruleset\
+\n\nOnly continue if you are sure about making the changes.  To keep your current\
+\niptables rules as they are, quit now by pressing ctl-c.  Otherwise, make the\
+\nqueued changes by pressing any other key....\n";read -rsn 1;read -rst 0.001 -n3
+                 j=$(($($iptablespath -wnL INPUT --line-number|$awkpath 'END {print $1}')))
+                 for ((;j>0;j--)); do
+                      [[ "$($iptablespath -wnL INPUT $j 2>/dev/null)" =~ poofitee_knock ]] && ([[ "$($iptablespath -wD INPUT $j 2>/dev/null;echo "$?")" == "0" ]] && echo "Removed INPUT chain rule $j assuming it was from the previous, obsolete poofitee knock ruleset" || printf "Failed 5")
+                 done
+# start making rules here
+                 [[ "$($iptablespath -wN poofitee_knock_check 2>/dev/null;echo "$?")" == "0" ]] || $iptablespath -wF poofitee_knock_check 2>/dev/null
+                 [[ "$($iptablespath -wN poofitee_knock_new_knock 2>/dev/null;echo "$?")" == "0" ]] || $iptablespath -wF poofitee_knock_new_knock 2>/dev/null
+                 [[ "$($iptablespath -wN poofitee_knock_authorize 2>/dev/null;echo "$?")" == "0" ]] || $iptablespath -wF poofitee_knock_authorize 2>/dev/null
+                 [[ "$($iptablespath -wN poofitee_knock_seniorize 2>/dev/null;echo "$?")" == "0" ]] || $iptablespath -wF poofitee_knock_seniorize 2>/dev/null
+                 [[ "$($iptablespath -wN poofitee_knock_juniorize 2>/dev/null;echo "$?")" == "0" ]] || $iptablespath -wF poofitee_knock_juniorize 2>/dev/null
+                 [[ "$($iptablespath -wN poofitee_knock_sophomorize 2>/dev/null;echo "$?")" == "0" ]] || $iptablespath -wF poofitee_knock_sophomorize 2>/dev/null
+                 [[ "$($iptablespath -wN poofitee_knock_customexit 2>/dev/null;echo "$?")" == "0" ]] || $iptablespath -wF poofitee_knock_customexit 2>/dev/null
+                 j=0
+                 while ! [[ -z "${knockproto[$(($j + 1))]}" ]];do
+                      j=$(( $j + 1 ))
+                      [[ "$($iptablespath -wA poofitee_knock_check ${knockproto[$j]} -m recent --name poofitee_knock_port$j --rcheck -j RETURN;echo "$?")" == "0" ]] || printf "Failed 1"
+                 done
+                 j=0
+                 while ! [[ -z "${knockproto[$(($j + 1))]}" ]];do
+                      j=$(( $j + 1 ))
+                      [[ "$($iptablespath -wA poofitee_knock_check ${knockproto[$j]} -m recent --name poofitee_knock_port$j --set -j poofitee_knock_new_knock;echo "$?")" == "0" ]] || printf "Failed 2"
+                      [[ "$($iptablespath -wA poofitee_knock_customexit ${knockproto[$j]} ${testtarget[$j]};echo "$?")" == "0" ]] || printf "Failed 3"
+                 done
+                 [[ "$($iptablespath -wA poofitee_knock_customexit -j LOG 2>/dev/null;echo "$?")" == "0" ]] || printf "Failed 4"
+                 [[ "$($iptablespath -wA poofitee_knock_customexit -j LOG --log-prefix "poofitee_knock ERROR knock_portcustomexit" -m comment --comment "There is no known reason for this to happen.  Troubleshoot if it does" 2>/dev/null;echo "$?")" == "0" ]] || printf "Failed 5"
+                 [[ "$($iptablespath -wA poofitee_knock_customexit -j DROP 2>/dev/null;echo "$?")" == "0" ]] || printf "Failed 6"
+                 [[ "$($iptablespath -wA poofitee_knock_new_knock -m recent --name poofitee_knock_senior --rcheck --seconds $(( $j * 12 )) --reap -j poofitee_knock_authorize 2>/dev/null;echo "$?")" == "0" ]] || printf "Failed 7"
+                 [[ "$($iptablespath -wA poofitee_knock_new_knock -m recent --name poofitee_knock_junior --rcheck --seconds $(( $j * 12 )) --reap -j poofitee_knock_seniorize 2>/dev/null;echo "$?")" == "0" ]] || printf "Failed 8"
+                 [[ "$($iptablespath -wA poofitee_knock_new_knock -m recent --name poofitee_knock_sophomore --rcheck --seconds $(( $j * 12 )) --reap -j poofitee_knock_juniorize 2>/dev/null;echo "$?")" == "0" ]] || printf "Failed 9"
+                 [[ "$($iptablespath -wA poofitee_knock_new_knock -m recent --name poofitee_knock_freshman --rcheck --seconds $(( $j * 12 )) --reap -j poofitee_knock_sophomorize 2>/dev/null;echo "$?")" == "0" ]] || printf "Failed 10"
+                 [[ "$($iptablespath -wA poofitee_knock_new_knock -m recent --name poofitee_knock_freshman --set -j LOG --log-prefix "poofitee knock freshman " -m comment --comment "poofitee_knock:This will schedule its blacklisting for couple mins from now" 2>/dev/null;echo "$?")" == "0" ]] || printf "Failed 11"
+                 [[ "$($iptablespath -wA poofitee_knock_new_knock -j poofitee_knock_customexit 2>/dev/null;echo "$?")" == "0" ]] || printf "Failed 12"
+                 [[ "$($iptablespath -wA poofitee_knock_authorize -m recent --name poofitee_knock_authorized --set -j LOG --log-prefix "poofitee knock authorized " 2>/dev/null;echo "$?")" == "0" ]] || printf "Failed 13"
+                 [[ "$($iptablespath -wA poofitee_knock_authorize -j poofitee_knock_customexit 2>/dev/null;echo "$?")" == "0" ]] || printf "Failed 14"
+                 [[ "$($iptablespath -wA poofitee_knock_seniorize -m recent --name poofitee_knock_senior --set -j LOG --log-prefix "poofitee knock senior " -m comment --comment "poofitee_knock" 2>/dev/null;echo "$?")" == "0" ]] || printf "Failed 15"
+                 [[ "$($iptablespath -wA poofitee_knock_seniorize -j poofitee_knock_customexit 2>/dev/null;echo "$?")" == "0" ]] || printf "Failed 16"
+                 [[ "$($iptablespath -wA poofitee_knock_juniorize -m recent --name poofitee_knock_junior --set -j LOG --log-prefix "poofitee knock junior " -m comment --comment "poofitee_knock" 2>/dev/null;echo "$?")" == "0" ]] || printf "Failed 17"
+                 [[ "$($iptablespath -wA poofitee_knock_juniorize -j poofitee_knock_customexit 2>/dev/null;echo "$?")" == "0" ]] || printf "Failed 18"
+                 [[ "$($iptablespath -wA poofitee_knock_sophomorize -m recent --name poofitee_knock_sophomore --set -j LOG --log-prefix "poofitee knock sophomore " -m comment --comment "poofitee_knock" 2>/dev/null;echo "$?")" == "0" ]] || printf "Failed 19"
+                 [[ "$($iptablespath -wA poofitee_knock_sophomorize -j poofitee_knock_customexit 2>/dev/null;echo "$?")" == "0" ]] || printf "Failed 20"
+                 [[ "$($iptablespath -wI INPUT -m recent --name poofitee_knock_authorized --rcheck -j ACCEPT 2>/dev/null;echo "$?")" == "0" ]] || printf "Failed 21"
+                 [[ "$($iptablespath -wI INPUT -m conntrack --ctstate NEW -j poofitee_knock_check 2>/dev/null;echo "$?")" == "0" ]] || printf "Failed 22"
             else
                  echo "Setting strict rules here"
                  if_first_knock_is_ACK_message="If you intend for your server to be invisible to the world, at least beyond the\
@@ -485,15 +461,21 @@ EOF
 \nadvised for minimum visibility). Any other key will turn off the reject response\
 \nto this knock: (r/k/...)"
                  get_operator_knock_choices
+                 for (( j=1;j<i;j++ )); do
+                      printf "$iptablespath -wA poofitee_knockstage$j${knockproto[$j]}\n"
+                 done
                  printf "\n\nYour current iptables ruleset is about to be changed to reflect your knock\
 \nentries just made.  The following changes are about to be made:\
-\n\n  -- All INPUT chain rules will be removed that contain the letters \"knock\" in\
-\n        sequence in their comment\
+\n\n  -- All INPUT chain rules will be removed that contain the string\
+\n        \"poofitee_knock\" in their comment\
 \n\n  -- INPUT chain will receive all new knock rules that belong there, being\
 \n        placed adjacent and prior to current non-knock rules referencing the\
 \n        respective interface\
-\n\n  -- Chains knockerreap, knockersort, knockers, and all knockstages will be\
-\n        flushed and reloaded new\
+\n\n  -- Poofitee chains knockerreap, knockersort, knockers, and all knockstages\
+\n        will be created new\
+\n\n  -- Poofitee chains knock_check, knock_new_knock, knock_portcustomexit,\
+\n        and others will be de-referenced and abandoned.  They are only\
+\n        used in the loose knock ruleset\
 \n\nOnly continue if you are sure about making the changes.  To keep your current\
 \niptables rules as they are, quit now by pressing ctl-c.  Otherwise, make the\
 \nqueued changes by pressing any other key....\n";read -rsn 1;read -rst 0.001 -n3
