Update POOFITEE

diff --git a/POOFITEE b/POOFITEE
--- a/POOFITEE
+++ b/POOFITEE
@@ -390,7 +390,7 @@ if ! [[ -z $mailpath ]];then
           echo
           get_sendto_emailadds onlyneed1 optional
           if [[ -z "$mailadd" ]]; then break;fi
-          read -e -r -i "$mailadd" -p "$mailcmd " mailadd
+          read -eri "$mailadd" -p "$mailcmd " mailadd
           if ! [[ "$mailadd" =~ ^(([-a-zA-Z0-9\!#\$%\&\'*+/=?^_\`{\|}~]+|(\"([][,:;<>\&@a-zA-Z0-9\!#\$%\&\'*+/=?^_\`{\|}~-]|(\\\\[\\ \"]))+\"))\.)*([-a-zA-Z0-9\!#\$%\&\'*+/=?^_\`{\|}~]+|(\"([][,:;<>\&@a-zA-Z0-9\!#\$%\&\'*+/=?^_\`{\|}~-]|(\\\\[\\ \"]))+\"))+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$ ]];then
                continue
           fi
@@ -836,7 +836,7 @@ if ! [[ -z "$iptabsavepath""$netfiltperspath" ]];then
      $([[ -z "$iptabsavepath" ]] && printf "$netfiltperspath save" || printf "$iptabsavepath") &>/dev/null 
      backup_result="$?"
      [[ "$backup_result" ]] && printf "\nA copy of your $1 iptables ruleset is backed up in\
-\n\n$poofitee_home_dir/iptables_ruleset.$current_time\n\n"
+\n\n$poofitee_home_dir/iptables_ruleset.$current_time\n"
 fi
 if [[ "$backup_result" ]] && ! [[ -z "$ipsetpath" ]] && "$ipsetpath list" &>/dev/null]];then
      "$ipsetpath save > /etc/iptables/ipset.sets" 2>/dev/null
@@ -933,7 +933,7 @@ get_operator_knock_choices () {
 \nyou don\'t care to get any fancier.  You may include mask-flag spec or other\
 \niptables matching options beyond this, if you know them, except the -j target,\
 \n-g chain, -m recent, and -m comment iptables modules/options):\n\
-\n";knockproto[$i]="-p tcp --syn ";read -e -i "${knockproto[$i]}" knockproto[$i]
+\n";knockproto[$i]="-p tcp --syn ";read -eri "${knockproto[$i]}" knockproto[$i]
                       testtarget[$i]=" -j DROP"
                       if [[ "${knockproto[$i]}" =~ \ --tcp-flags\ .*ACK\ .*ACK ]] ; then
 #                      if [[ "${knockproto[$i]}" =~ \ --tcp-flags\ *[^[:space:]g]*\ *ACK\  ]] ; then
@@ -1731,7 +1731,7 @@ if [[ -z $sendmail_works ]];then
 \nserver somewhere to authenticate the outgoing email traffic (it's come to this\
 \nbecause of spammers).  Enter now the email account name to use for an outgoing\
 \nemail server based on its ability to accept sign-on through this scripting\
-\nyou're installing.  Preferrably not too strict accepting sign-on because this\
+\nyou're installing.  Preferably not too strict accepting sign-on because this\
 \nscript uses the mid-tier security of standard smtp protocol (your email\
 \ncredentials, including password, are stored in this scripting and sent encrypted\
 \nbut via standard smtp protocol) rather than upper-tier security (\"OAuth 2.0\" -\
@@ -1754,11 +1754,12 @@ create_tmp_timeouttry_script
 while true;do  #this loop allows user to change the email account for outbound server & builds connect.txt file
      while true; do #this loop forces an address to be chosen from the bunch, then goes through all connections found for it
           [[ -z "$outemailadd" ]] && outemailadd=$(cat "$poofitee_home_dir/outemailadd" 2>/dev/null)
-          bunch="$outemailadd"
-          ! [[ -z "$outemailadd" ]] && bunch+="\n"
-          bunch+="$toemailadds"
-          ! [[ -z "$toemailadds" ]] && bunch+="\n"
-          bunch+="$inemailadds"
+          bunch=""
+          ! [[ -z "$outemailadd" ]] && bunch="$outemailadd"
+          (! [[ -z "$bunch" ]] && ! [[ "${bunch,, -2}" == "\n" ]] && ! [[ -z "$toemailadds" ]]) && bunch+="\n"
+          ! [[ -z "$toemailadds" ]] && bunch+="$toemailadds"
+          (! [[ -z "$bunch" ]] && ! [[ "${bunch,, -2}" == "\n" ]] && ! [[ -z "$inemailadd" ]]) && bunch+="\n"
+          ! [[ -z "$inemailadd" ]] && bunch+="$inemailadd"
           get_1_addr_from_bunch "$bunch"
           outemailadd="$emailadd";outemailacct="$emailacct";outemaildomain="$emaildomain";outtopdomain="$topdomain";outemailprovider="$emailprovider";outemailpw="$emailpw"
           printf "determining best option for outgoing email server login.  You should be doing\
@@ -1883,11 +1884,11 @@ postfix_already_conf=True # set this to True or just anything non-empty
           install_rc () {
 poofitee_home_dir="$( cat poofitee_home_dir )"
 # "$($sedpath 's/,/\n/g' <"$poofitee_home_dir/toemailadds")"
-inemailadds=""
-inemailadds="$( [[ -f "$poofitee_home_dir/outemailadd" ]] && cat "$poofitee_home_dir/outemailadd" 2>/dev/null || [[ -f "$poofitee_home_dir/toemailadds" ]] && $sedpath 's/,/\n/g' <"$poofitee_home_dir/toemailadds" )"
+#inemailadd=""
+#inemailadd="$( [[ -f "$poofitee_home_dir/outemailadd" ]] && cat "$poofitee_home_dir/outemailadd" 2>/dev/null || [[ -f "$poofitee_home_dir/toemailadds" ]] && $sedpath 's/,/\n/g' <"$poofitee_home_dir/toemailadds" )"
 #WORKING ON: nice selector from "$poofitee_home_dir/successlogins"
 
-inemailacct="${inemailadd%@*}";inemailprovider="${inemailadd#*@}";inemaildomain="${inemailprovider%.*}";intopdomain="${inemailprovider#*.}";inemailsubdomain="pop";
+#inemailacct="${inemailadd%@*}";inemailprovider="${inemailadd#*@}";inemaildomain="${inemailprovider%.*}";intopdomain="${inemailprovider#*.}";inemailsubdomain="pop";
 # rm "$poofitee_home_dir/successlogins" 2>/dev/null
 create_tmp_timeouttry_script
 clear
@@ -1900,11 +1901,12 @@ while true;do
 \n\n  Enter the email address now from which this system will retrieve instructions\
 \nto itself that you or others will send:\n"
 #     printf -- "$line"
-     bunch="$inemailadds"
-     ! [[ -z "$inemailadds" ]] && bunch+="\n"
-     bunch+="$outemailadd"
-     ! [[ -z "$outemailadd" ]] && bunch+="\n"
-     bunch+="$toemailadds"
+     bunch=""
+     ! [[ -z "$inemailadd" ]] && bunch="$inemailadd"
+     (! [[ -z "$bunch" ]] && ! [[ "${bunch,, -2}" == "\n" ]] && ! [[ -z "$outemailadd" ]]) && bunch+="\n"
+     ! [[ -z "$outemailadd" ]] && bunch+="$outemailadd"
+     (! [[ -z "$bunch" ]] && ! [[ "${bunch,, -2}" == "\n" ]] && ! [[ -z "$toemailadds" ]]) && bunch+="\n"
+     ! [[ -z "$toemailadds" ]] && bunch+="$toemailadds"
      get_1_addr_from_bunch "$bunch"
           inemailadd="$emailadd";inemailacct="$emailacct";inemaildomain="$emaildomain";intopdomain="$topdomain";inemailprovider="$emailprovider";inemailpw="$emailpw"
               printf "Configuring for that email account.  Remember, you should be doing\
@@ -2025,7 +2027,7 @@ done
 # identifies itself with the term "email-reader"
 # in its comments. The script searching for that
 # port-match and launching this script is called
-# process_source_ip.sh.  By maintaining a dynamic
+# process_logfile_line.  By maintaining a dynamic
 # blacklist for a while you'll better be able
 # to determine a good port for you.
 
@@ -2111,8 +2113,8 @@ port=110;MAIL_PROT="pop3"
 [ ! -z \${3,S} ] && [ \${3,I} == "i" ] && MAIL_PROT="imap"
 #echo \$port
 #echo "<\$MAIL_PROT>"
-#echo "\$MAIL_FROM"
-accountname=\$(echo "\$MAIL_FROM" | $awkpath -F@ '{print \$1}');domainname=\$(echo  "\$MAIL_FROM" | $awkpath -F@ '{print \$2}')
+#echo "\$inemailadd"
+accountname=\$(echo "\$inemailadd" | $awkpath -F@ '{print \$1}');domainname=\$(echo  "\$inemailadd" | $awkpath -F@ '{print \$2}')
 #echo "\$accountname and \$MAIL_PROT.\$domainname"
 #echo "/dev/tcp/\$MAIL_PROT.\$domainname/\$port"
 exec 5>&-;wait
@@ -2267,11 +2269,13 @@ chmod 700 "$poofitee_home_dir/email_fetch_parse"
 # TODO: iptables entry to log port knock for email reader
 # belongs inserted just before both whitelist and blacklist - use the lower line number of them both
 until read -erp "Enter a port number you will knock to initiate email to be read: " emailport; [[ "$emailport" =~ ^[0-9]{1,5}$ ]] && [[ $(( $emailport )) -le 65536 ]];do
-    printf "\nThe port number must be a number between 0 and 65535 inclusive\n"
+    printf "\nThe port number must be a number between 0 and 65535 inclusive,\
+\nbut 0 can be deemed by security-conscious routers to be invalid to traverse\
+\nthe Internet.\n"
 done
 emailproto="tcp"
 if [ -f "/etc/protocols" ];then
-     until read -erp "Enter the protocol you will use in that knock: " emailproto -i "$emailproto" 2>/dev/null; [[ "$($awkpath '{print $1" "$2" "$3}' < "/etc/protocols"|$greppath -wcm 1 "$emailproto")" == "1" ]];do
+     until read -eri "$emailproto" -p "Enter the protocol you will use in that knock: " emailproto; [[ "$($awkpath '{print $1" "$2" "$3}' < "/etc/protocols"|$greppath -wcm 1 "$emailproto")" == "1" ]];do
          printf "\nThe protocol must be available in /etc/protocols\n"
      done
 else
@@ -2366,7 +2370,7 @@ if ! [[ -z "$toemailaddsIP" ]];then
 fi
 # "$poofitee_home_dir/newdynip.sh"
 printf "The notification email you'd receive should refer to this computer by what name?"
-pcname=$(while read -e -r -i "$(hostname)" sysname;do if ! [[ -z "$sysname" ]];then echo "$sysname";break;fi;done)
+pcname=$(while read -eri "$(hostname)" sysname;do if ! [[ -z "$sysname" ]];then echo "$sysname";break;fi;done)
 echo
 if [[ "$($curlpath http://ipecho.net/plain)" =~ ^((1?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])\.){3}(1?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])$ ]];then 
      printf "To learn any new IP address gotten, this computer will interrogate a public\nservice, \
@@ -2376,7 +2380,7 @@ else
 default is shown below, but is NOT WORKING now.  Change it to suit you:"
 fi
 #The following line is not yet tested after changing from dig to curl
-resolver="$(while read -e -i "$curlpath http://ipecho.net/plain" resolver;do 
+resolver="$(while read -ei "$curlpath http://ipecho.net/plain" resolver;do 
      echo "$resolver";break;
 done)"
 
@@ -2578,7 +2582,7 @@ end_warnings () {
 \nbetter reason for doing so than that."
 }
 get_1_addr_from_bunch() {
-#one arg: a bunch of newline delimited email addresses
+#one arg: a bunch of newline delimited email addresses, except no newline following last entry
           emailadds="$1"
           scratchpad="${emailadds%%'\n'*}"
           emailaddid=1 ;horizptr="${#scratchpad}"
@@ -3950,14 +3954,14 @@ until ! [[ -z "$answer" ]];do
                  if [ -z "$been_here_before" ];then
                       ensure_connection
                       if [[ "$installerpath" =~ apt-get|pacman ]];then
-                           printf "Installation of\n$notinstalled\n\nis required next.  Press u to update your system's package installer first,\
+                           printf "Installation of\n$notinstalled\nis required next.  Press u to update your system's package installer first,\
 $([[ "$installerpath" =~ apt-get ]] && printf "\npress b to both update your system's package installer & have it run autoremove,")\
 \nany other letter or number key not to update the installer first.  \n"
                            press_a_key u $([[ "$installerpath" =~ apt-get ]] && printf "b" || printf "<other-letter-or-number>")
                            if [[ "$installerpath" =~ apt-get ]] && [[ "$REPLY" =~ [Bb] ]];then
                                 clear
                                 installeranswer="$REPLY"
-                                printf "Cleaning up with apt-get autoremove\n"
+                                printf "\r\033[KCleaning up with apt-get autoremove\r"
                                 while true;do ps a|$greppath -v grep|$greppath preconfigure &>/dev/null || printf ".";sleep 1;done &
                                 progress_dots="$!"
                                 apt-get autoremove -y &>/dev/null
@@ -3966,7 +3970,7 @@ $([[ "$installerpath" =~ apt-get ]] && printf "\npress b to both update your sys
                            fi
                            if [[ "$REPLY" =~ [UuBb] ]];then
                                 clear
-                                printf "Updating your system\'s package installer\n" # in arch, do pacman -Syuu
+                                printf "\r\033[KUpdating your system\'s package installer\r" # in arch, do pacman -Syuu
                                 if [[ "$installerpath" =~ apt-get ]];then
                                     while true;do ps a|$greppath -v grep|$greppath preconfigure &>/dev/null || printf ".";sleep 1;done &
                                     progress_dots="$!"
@@ -3979,7 +3983,7 @@ $([[ "$installerpath" =~ apt-get ]] && printf "\npress b to both update your sys
                            been_here_before="."
                       fi
                  fi
-                 printf "\r\033[KInstalling $not_installed_single_line\n"
+                 printf "\r\033[KInstalling $not_installed_single_line\r"
                  eval "$xargspath -a <(printf "$not_installed_single_line") -r -- $sudopath $installerpath" 2>/dev/null
                  what_needs_to_be_installed &>/dev/null
 #                 press_a_key
@@ -4031,13 +4035,13 @@ $([[ "$installerpath" =~ apt-get ]] && printf "\npress b to both update your sys
                  elif [ $? != "0" ] && [ "$(what_needs_to_be_installed;echo "$?")" != "0" ];then
                       if [[ -z "$update_tried" ]];then
                            update_tried="yes"
-                           printf "Updating your system\'s package installer\n"
+                           printf "\r\033[KUpdating your system\'s package installer\r"
                            while true;do ps a|$greppath -v grep|$greppath preconfigure &>/dev/null || printf ".";sleep 1;done &
                            progress_dots="$!"
                            apt-get update &>/dev/null
                            kill $progress_dots; trap 'kill $progress_dots' SIGTERM
                       else
-                           printf "The following $(what_needs_to_be_installed;echo "$?") packages failed to install:\n$notinstalled\
+                           printf "\r\033[KThe following $(what_needs_to_be_installed;echo "$?") packages failed to install:\n$notinstalled\
 \npress R to retry (recommended as long as progress is being made with repeated\
 \nretries), any other alpha-numeric key to ignore:\n"
                            press_a_key r "<other-letter-or-number>" || break
@@ -4063,7 +4067,7 @@ $([[ "$installerpath" =~ apt-get ]] && printf "\npress b to both update your sys
         if ! [[ -z "$ipsetpath" ]];then
             if $ipsetpath list -t >&/dev/null;then :;else
                 if $lsmodpath|$greppath -e '^xt_set ' -e '^ip_set '  -e '^ipset ' -e '^xtset ' &>/dev/null;then :;else
-                    showthis "The ipset loadable kernel module is not automatically loaded for you.  \
+                    showthis "\nThe ipset loadable kernel module is not automatically loaded for you.  \
 This just happens to be the case with the particular Linux distro you're using.  \
 You'll have to load the ipset module manually and restart poofitee installer.  Here \
 is a web page that may help you with that:\
@@ -4081,11 +4085,11 @@ is a web page that may help you with that:\
                 [[ -z "$poofitee_home_dir" ]] && poofitee_home_dir="$poofitee_home_dir"
                 [[ -z "$poofitee_home_dir" ]] && poofitee_home_dir="/home/poofitee"
                 clear
-                printf "Specify a home directory which will be created for user poofitee, which is where\
+                printf "\nSpecify a home directory which will be created for user poofitee, which is where\
 \nthese scripts will be installed.  No deeper subdirectory will be used than what\
 \nyou specify here, so include any final isolating or descriptive subdirectory\
 \nlevel you will want:\n"
-               read -e -r -i "$poofitee_home_dir" poofitee_home_dir
+               read -eri "$poofitee_home_dir" poofitee_home_dir
                echo
                echo "poofitee ALL=NOPASSWD:ALL" > /etc/sudoers.d/poofitee
 #                 echo "poofitee ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/poofitee
@@ -4149,7 +4153,7 @@ is a web page that may help you with that:\
                      directory_for_list_files="$([[ -f "$poofitee_home_dir/directory_for_list_files" ]] && cat "$poofitee_home_dir/directory_for_list_files")"
                      [[ -z "$directory_for_list_files" ]] && directory_for_list_files="$PWD"
                 fi
-                while printf "\nEnter the directory name where you want the firewall $ipsetpath sets to be saved to:\n";read -er -i "$directory_for_list_files" directory_for_list_files;do
+                while printf "\nEnter the directory name where you want the firewall $ipsetpath sets to be saved to:\n";read -eri "$directory_for_list_files" directory_for_list_files;do
                      [[ -d "$directory_for_list_files" ]] && break
                      printf "\nNot a valid directory. Try again.  "
                      press_a_key
@@ -4168,7 +4172,7 @@ is a web page that may help you with that:\
                     directory_for_list_files="$([[ -f "$poofitee_home_dir/directory_for_list_files" ]] && cat "$poofitee_home_dir/directory_for_list_files")"
                     [[ -z "$directory_for_list_files" ]] && directory_for_list_files="$PWD"
                 fi
-                while printf "\nEnter the directory name containing the files that you want the firewall $ipsetpath sets to be configured from:\n";read -er -i "$directory_for_list_files" directory_for_list_files;do
+                while printf "\nEnter the directory name containing the files that you want the firewall $ipsetpath sets to be configured from:\n";read -eri "$directory_for_list_files" directory_for_list_files;do
                      [[ -d "$directory_for_list_files" ]] && break
                      printf "\nNot a valid directory. Try again.  "
                      press_a_key
