Update POOFITEE

diff --git a/POOFITEE b/POOFITEE
--- a/POOFITEE
+++ b/POOFITEE
@@ -115,9 +115,8 @@
 install_openall () {
 (cat <<EOF
 #!/bin/bash
-
 #This script will add or remove to iptables (IPv4) poofitee_fw_s_whitelist and poofitee_fw_d_whitelist chains
-
+# It is referenced by email_fetch_parse and by process_logfile_line; can also be launched manually if given an ip address
 #This test will allow CIDR-type consolidated IPv4 address ranges
 if ! [[ \$1 =~ ^((1?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])\.){3}(1?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])((/[0-2]?[0-9])|(/3[0-2]))?$ ]]; then
     echo "This script requires a valid IP address besides the script name" >> "\$0.log";
@@ -192,13 +191,22 @@ set_notinstalled_var () {
 [[ -z $nicepath ]] && notinstalled+="coreutils\n"
 [[ -z $sendmail_works ]] && [[ -z $postmappath ]] && notinstalled+="postmap\n"
 }
+
 press_a_key () {
 printf "press $(! [[ -z "$1$2" ]] && printf "$1/$2" || printf "any key"), Ctrl-c aborts...";read -rsn 1;read -rst 0.001 -n3 discard
 [[ "$REPLY" == "$1" ]] && return 0 || return 1
 }
+
 install_tail_f_lines_and_receiving_script () {
 (cat <<SCRIPT_END
 #!/bin/bash
+#if ! (
+$ipsetpath add blacklist \$1 comment \$2 >/dev/null 2>/dev/null
+# ); then
+# list too full, swap it out
+#find the highest blacklist number, make a new list one higher, then swap and save
+#     next_blacklist_number="$(/sbin/ipset list -t|/bin/grep -i "^name: blacklist"|/usr/bin/awk '{print substr($2,10)+1}')"
+#fi # By putting this here, we'll reduce number of duplicate calls to this script.  Port knocking may be adversely affected, however, for the knocks that need to get logged (example: whitelisting from loose rules) if they arrive before t$
 
 lockfile_dir="$poofitee_home_dir/ramdisk" # Purpose is for easy copy-paste-reuse of lock lines
 
@@ -215,8 +223,8 @@ $greppath -- "-A poofitee_fw_s_blacklist" < /etc/iptables/rules.v4 > "$poofitee_
 }
 
 save_iptables () {
-# skip this if another instance of this script is waiting to run
 # echo "\$(date) - Entered save ruleset" >> "\$0.log"
+# skip this if another instance of this script is waiting to run
 # pslinecount="\$(\$greppath "\$(ps > "$poofitee_home_dir/ramdisk/psout";$greppath "^\$$" < "$poofitee_home_dir/ramdisk/psout"|$sedpath -n 's/\\S*\\s*\\S*\\s*\\S*\\s*//p')" < "$poofitee_home_dir/ramdisk/psout"|$wcpath -l)"
 # echo "\$(date) - pslinecount=\$pslinecount" >> "\$0.log"
 #!!!!!!! get this functional when it gets launched by poofitee user from crontab
@@ -767,7 +775,6 @@ printf "\n\nYour current iptables ruleset is about to be changed to reflect your
                       printf "Note that the file name is different than the one saved before" || \
                       ( printf "Your new iptables ruleset did NOT get backed up correctly.  You should\"
 \ntroubleshoot the problem, correct it, and start this install over again.\n"; exit )
-                 ################### HERE WOULD BE A DIFFERENT INSTALL AND LAUNCH THE CRON LINE, UNIQUE TO LOOSE RULES B/C THE WHITELIST ADDITION
                  install_openall
                  install_firewall_cronentries
                  conf_postfix
@@ -954,7 +961,8 @@ if [ -d /usr/share/netfilter-persistent/plugins.d ];then
 fi
             (cat <<-BUILDIPTABLES.SH_END
 	#!/bin/bash
-	ipset create blacklist hash:ip >/dev/null 2>/dev/null
+	ipset create blacklist hash:ip comment >/dev/null 2>/dev/null
+#	ipset create blacklist hash:ip comment hashsize 64 >/dev/null 2>/dev/null
 	$iptablespath -wP OUTPUT ACCEPT
 	$iptablespath -wN poofitee_fw_d_blacklist  2>/dev/null
 	$iptablespath -wN poofitee_fw_d_privateIPs  2>/dev/null
@@ -974,7 +982,7 @@ fi
 	! ($iptablespath -wnvL INPUT                         |$greppath -- " poofitee_fw_s_static_trusted  all  --  "                                                                |$greppath "poofitee_firewall") && ($iptablespath -wA INPUT -j poofitee_fw_s_static_trusted -m comment --comment "poofitee_firewall"  2>/dev/null || printf "Failed")
 	! ($iptablespath -wnvL INPUT                         |$greppath -- " poofitee_fw_s_whitelist  all  --  "                                                                     |$greppath "poofitee_firewall") && ($iptablespath -wA INPUT -j poofitee_fw_s_whitelist -m comment --comment "poofitee_firewall"  2>/dev/null || printf "Failed")
 	! ($iptablespath -wnvL INPUT                         |$greppath -- " poofitee_fw_s_privateIPs  all  --  $external_net_interface"                                             |$greppath "poofitee_firewall") && ($iptablespath -wA INPUT -i $external_net_interface -j poofitee_fw_s_privateIPs -m comment --comment "poofitee_firewall"  2>/dev/null || printf "Failed")
-	! ($iptablespath -wnvL INPUT                         |$greppath -- " DROP       all  --  "                                           |$greppath -- " match-set blacklist src"|$greppath "poofitee_firewall") && ($iptablespath -wA INPUT -m set --match-set blacklist src -j DROP -m comment --comment "poofitee_firewall"  2>/dev/null || printf "Failed")
+	! ($iptablespath -wnvL PREROUTING -t raw             |$greppath -- " DROP       all  --  "                                           |$greppath -- " match-set blacklist src"|$greppath "poofitee_firewall") && ($iptablespath -wA PREROUTING -t raw -m set --match-set blacklist src -j DROP -m comment --comment "poofitee_firewall"  2>/dev/null || printf "Failed")
 	! ($iptablespath -wnvL INPUT                         |$greppath -- " poofitee_fw_s_blacklist  all  --  "                                                                     |$greppath "poofitee_firewall") && ($iptablespath -wA INPUT -j poofitee_fw_s_blacklist -m comment --comment "poofitee_firewall"  2>/dev/null || printf "Failed")
 	! ($iptablespath -wnvL INPUT                         |$greppath -- " LOG        all  --  "                |$greppath -- " --log-level 4 --log-prefix \"INPUT chain termed \""|$greppath "poofitee_firewall") && ($iptablespath -wA INPUT -i $external_net_interface -j LOG --log-level 4 --log-prefix "INPUT chain termed " -m comment --comment "poofitee_firewall"  2>/dev/null || printf "Failed")
 	! ($iptablespath -wnvL INPUT                         |$greppath -- " DROP       all  --  "                                                                                   |$greppath "poofitee_firewall"|$greppath -v ) && ($iptablespath -wA INPUT -i $external_net_interface -j DROP -m comment --comment "poofitee_firewall"  2>/dev/null || printf "Failed")
@@ -2568,7 +2576,7 @@ newemailconfigwarning="Installing a new configuration is\
              install_dynIPch
         fi
         if [[ "$answer" =~ p ]];then
-            install_port_knocking
+             install_port_knocking
              advise_to_verify_persistency
         fi
      fi
